### ISSUE TITLE
Config CSS does not load if child theme is used

### ISSUE THREAD

**Issue by TerrapinSoftware** [swissup/theme-frontend-absolute#1]
The CSS config data is saved in e.g. `media/swissup/absolute/css/admin_backend.css`. The code that generates the CSS link in `module-theme-editor/Block/Html/Head.php`in `getBackendCss()`, however, uses the theme name and looks e.g. for `media/my/theme/css/admin_backend.css`.

That method should walk the theme chain until a "swissup" theme has been processed before giving up. This makes it possible to implement a child theme that derives from the Absolute theme (which is the preferred way to alter a theme).

**Comment by vovayatsyuk** [comment]
Sorry for the late response. We are going to improve our [theme-editor module](https://github.com/swissup/module-theme-editor/issues/7) so it will work with child themes. No ETA, unfortunately.
